export const editableDefaults: Record<string, string> = {
  'brand-logo-text': 'Dispulse',
  'nav-home': 'Home',
  'nav-services': 'Services',
  'nav-work': 'Work',
  'nav-faq': 'FAQ',
  'nav-contact': 'Contact',
  'nav-cta': 'Get in Touch',
  'hero-badge': 'Creative Studio',
  'hero-title': 'Build Brands That',
  'hero-subtitle': 'Move Culture',
  'hero-description': 'We help creators, esports teams, and modern brands build identity, community, and long-term relevance through strategic social media.',
  'hero-cta-primary': 'Start a Project',
  'hero-cta-secondary': 'View Our Work',
  'hero-stat-value-1': '45K+',
  'hero-stat-label-1': 'Followers Grown',
  'hero-stat-value-2': 'Premium',
  'hero-stat-label-2': 'Brand Positioning',
  'hero-stat-value-3': 'Long-Term',
  'hero-stat-label-3': 'Partnership Focus',
  'services-badge': 'Our Services',
  'services-title-main': 'Services built',
  'services-title-highlight': 'for brands that want to lead',
  'services-subtitle': 'Strategy, production, and partnership support designed to create durable growth in esports and beyond.',
  'services-card-title-0': 'Content Strategy & Production',
  'services-card-description-0': 'Long-form and social-first storytelling built to raise brand perception and grow durable audiences.',
  'services-card-title-1': 'Community Engagement',
  'services-card-description-1': 'Programs that build loyalty, keep players close, and turn audience participation into a repeatable system.',
  'services-card-title-2': 'Brand Partnerships & Outreach',
  'services-card-description-2': 'Targeted partner lists, positioning, and outreach that align with your long-term content direction.',
  'services-form-title': 'Schedule & Email',
  'services-form-email-label': 'Email Address',
  'services-form-date-label': 'Select Date',
  'services-form-success': 'Email sent successfully! Check your inbox.',
  'services-form-error': 'Please fill in all fields correctly.',
  'work-title': 'Our Work',
  'work-subtitle': "Real results for real clients. See how we've helped brands grow their social presence.",
  'work-category-0': 'Services: Content Development | Brand Outreach & Partnerships | Business Operations',
  'work-client-0': 'Fruity INC',
  'work-description-0': "FruityINC came to us during a key growth phase, looking to transition from a creator-led project into a structured, pitch-ready business. Our role was to help professionalise both the brands outward presence and its internal operations.",
  'work-results-title-0': 'Results:',
  'work-result-0-0': 'Led brand outreach and partnership conversations to open commercial opportunities',
  'work-result-0-1': 'Supported business operations, helping streamline workflows and decision-making',
  'work-result-0-2': 'Built a full, pitch-ready deck to position FruityINC as a viable partner for brands and collaborators',
  'work-result-0-3': 'Evolved into a structured, pitchable business with clear messaging and professional assets designed for partnerships and growth',
  'work-category-1': 'Services: Content Production & Strategy | Community Engagement | Brand Partnerships & Outreach',
  'work-client-1': 'Void Esports',
  'work-description-1': "Void Esports wanted to elevate their content and brand perception within the Fortnite ecosystem. The goal was to move away from short-form, trend-driven posts and toward long-form, documentary-style storytelling that builds authority and longevity.",
  'work-results-title-1': 'Results:',
  'work-result-1-0': 'Repositioned content as premium, story-driven media within the Fortnite ecosystem',
  'work-result-1-1': 'Strengthened brand identity and deepened community connection',
  'work-result-1-2': 'Built stronger foundations for long-term brand partnerships',
  'faq-title': 'Frequently Asked Questions',
  'faq-subtitle': 'Everything you need to know about our process and services',
  'faq-question-0': 'How does your process work?',
  'faq-answer-0': 'Our process is simple and streamlined: 1) Initial consultation to understand your goals, 2) We create a custom strategy tailored to your brand, 3) Content creation and scheduling, 4) Daily monitoring and engagement, 5) Weekly analytics and optimization, 6) Monthly reporting and strategy adjustments.',
  'faq-question-1': 'What is the step-by-step onboarding process?',
  'faq-answer-1': "Step 1: Book a discovery call where we discuss your brand, goals, and target audience. Step 2: We audit your current social media presence and competitors. Step 3: Sign the agreement and provide us with access to your accounts. Step 4: We create your content calendar for the first month. Step 5: Review and approve the initial content. Step 6: We launch your campaign and begin posting. Step 7: Ongoing optimization and monthly strategy sessions.",
  'faq-question-2': 'How long does it take to see results?',
  'faq-answer-2': 'Typically, clients start seeing noticeable engagement improvements within 2-4 weeks. Significant follower growth usually occurs around the 2-3 month mark. However, building a strong, engaged community is a long-term strategy. We recommend committing to at least 3-6 months for optimal results.',
  'faq-question-3': 'Do I need to provide content, or do you create it?',
  'faq-answer-3': "We handle everything! Our team creates all content including graphics, videos, captions, and hashtags. However, we do request occasional input from you such as product photos, behind-the-scenes footage, or specific announcements you'd like us to share. We'll provide a content calendar for your approval each month.",
  'faq-question-4': 'Which social media platforms do you manage?',
  'faq-answer-4': "We specialize in Instagram, TikTok, YouTube, Twitter/X, LinkedIn, and Facebook. We can manage one platform or create a comprehensive multi-platform strategy. During our consultation, we'll recommend which platforms make the most sense for your specific business and target audience.",
  'faq-question-5': 'What makes your service different from others?',
  'faq-answer-5': "Unlike agencies that treat you like a number, we provide personalized attention to every client. Our team stays on top of the latest trends, algorithm changes, and platform features. We focus on authentic engagement rather than vanity metrics, and we're transparent with our reporting. Plus, we're available for communication whenever you need us.",
  'faq-question-6': 'Can I cancel my service at any time?',
  'faq-answer-6': "Yes! While we require a minimum 3-month commitment to see results, you can cancel after that with 30 days notice. We want you to stay because you love our work, not because you're locked into a contract. No hidden fees or cancellation charges.",
  'faq-question-7': 'How do you measure success?',
  'faq-answer-7': "We track multiple metrics including follower growth, engagement rate, reach, impressions, website clicks, and conversions. You'll receive detailed monthly reports showing your progress. We also set specific KPIs during our initial consultation so we're always working toward your unique goals.",
  'faq-question-8': 'Will I have a dedicated account manager?',
  'faq-answer-8': "Absolutely! You'll be assigned a dedicated account manager who will be your main point of contact. They'll learn your brand inside and out and be available via email, phone, or scheduled calls. You'll also have access to our creative team and strategists as needed.",
  'faq-question-9': 'What information do you need to get started?',
  'faq-answer-9': "To get started, we need: 1) Access to your social media accounts (we'll guide you through secure access setup), 2) Brand guidelines, logos, and color schemes, 3) Any existing content you'd like us to use, 4) Information about your products/services, target audience, and competitors, 5) Your goals and any specific campaigns you have in mind. Don't worry, we'll walk you through everything!",
  'faq-cta-title': 'Still have questions?',
  'faq-cta-subtitle': "We're here to help! Reach out to us anytime.",
  'contact-title': 'Get in Touch',
  'contact-subtitle': "Ready to grow your social media presence? Let's talk about your goals.",
  'contact-info-email-title': 'Email Us',
  'contact-info-email-value': 'contact@dispulse.co',
  'contact-info-dm-title': 'DM Us on X',
  'contact-info-dm-link': 'x.com/dispulse',
  'contact-info-hours-title': 'Business Hours',
  'contact-info-hours-value': 'Mon - Fri: 8am - 6pm UK Time (Corporate clients)',
  'contact-social-title': 'Follow Us',
  'contact-social-x': 'X',
  'contact-social-tiktok': 'TikTok',
  'contact-social-linkedin': 'LinkedIn',
  'contact-success': "Thank you! We'll get back to you within 24 hours.",
  'contact-error': 'Something went wrong. Please try again.',
  'contact-form-name-label': 'Full Name *',
  'contact-form-email-label': 'Email Address *',
  'contact-form-company-label': 'Company Name',
  'contact-form-service-label': 'Service Interested In *',
  'contact-form-message-label': 'Tell us about your project *',
  'footer-brand-title': 'Dispulse',
  'footer-brand-description': 'Strategy, production, and partnerships for teams that want to lead culture.',
  'footer-explore-title': 'Explore',
  'footer-link-services': 'Services',
  'footer-link-work': 'Work',
  'footer-link-faq': 'FAQ',
  'footer-link-contact': 'Contact',
  'footer-social-title': 'Social',
  'footer-social-x': 'X / Twitter',
  'footer-social-tiktok': 'TikTok',
  'footer-social-linkedin': 'LinkedIn',
  'footer-signal-title': 'Signal',
  'footer-note': 'Drop a message and get a response within 24 hours.',
  'footer-cta-email': 'contact@dispulse.co',
  'footer-bottom-studio': 'Dispulse Studio',
  'footer-bottom-location': 'London, UK',
  'footer-bottom-year': '2024',
};
